---
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: ingress-service
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kibana-service
          servicePort: 5601
        path: /kibana/?(.*)
      - backend:
          serviceName: elasticsearch-service
          servicePort: 9200
        path: /elasticsearch/?(.*)
      - backend:
          serviceName: logstash-service
          servicePort: 9600
        path: /logstash_api/?(.*)
      - backend:
          serviceName: logstash-service
          servicePort: 5044
        path: /logstash/?(.*)
      - backend:
          serviceName: kibana-service
          servicePort: 5601
        path: /?(.*)
