---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-service:9200" ]
    xpack.monitoring.enabled: true
  logstash.conf: |
    input {
        beats {
        port => 5044
        }
    }
    
    output {
        elasticsearch {
        hosts => ["http://elasticsearch-service:9200"]
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        }
    }
  