---
- name: check if docker exists
  command: which docker 
  register: docker_stat
  ignore_errors: yes
    
- name: install docker if not already installed
  block:
    - name: update cache
      apt:
        update_cache: yes

    - name: install required packages
      apt:
        name: "{{ item }}"
      loop: "{{ docker_required_packages }}"

    - name: Add docker official GPG key
      apt_key:
        url: "{{ docker_gpg_key }}"
        state: present

    - name: add docker repository
      apt_repository:
        repo: "{{ docker_repo }}"
        state: present
    
    - name: update cache
      apt:
        update_cache: yes

    - name: install docker
      apt:
        name: "{{ item }}"
      loop: "{{ docker_packages }}"
      notify: restart docker

    - name: 'add users to docker group'
      user:
        name: '{{ item }}'
        groups: 'docker'
        append: 'yes'
      loop: "{{ docker_group_members }}"
  when: docker_stat.stdout == ""
    