---
- name: check if kubectl exists
  command: which kubectl
  register: kubestat
  ignore_errors: yes

- name: install kubectl if does not exist and make it executable
  block:
    - name: update cache
      apt:
        update_cache: yes

    - name: install apt-transport-https and gnupg2
      apt:
        name: "{{ item }}"
      loop: "{{ kubectl_required_packages }}"

    - name: Add kube official GPG key
      apt_key:
        url: "{{ kubectl_gpg_key }}"
        state: present

    - name: create kubernetes file
      file:
        path: "{{ kubelist_file }}"
        state: touch

    - name: Add kubectl packge repo to packages list
      lineinfile:
        insertafter: EOF
        line: "{{ kubectl_repo }}"
        path: "{{ kubelist_file }}"

    - name: update cache
      apt:
        update_cache: yes

    - name: install kubectl
      apt:
        name: kubectl
  when: kubestat.stdout == ""
    