filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
      - '/tmp/dockerfs/containers/*/*.log'
      - '/var/log/*.log'      
output.logstash:
  hosts: ["localhost:5044"]
  