---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/all.yml
  tasks:
    - name: Validate if required variables are available
      fail:
        msg: AWS_ACCESS_KEY or AWS_SECRET_KEY not defined
      when: aws_access_key is not defined or aws_secret_key is not defined
      no_log: true

    - name: read deploy yaml
      include_vars:
        name: deploy_host_names
        file: ../deploy_config.yml

    - include_role: 
        name: ec2_setup
      loop: "{{deploy_host_names['hosts']}}"
      loop_control:
        loop_var: elkhostname

- hosts: elkhosts
  gather_facts: true
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /opt/secrets/jenkinskeypair.pem
  roles:
    - role: ec2_provision
      vars:
        become: true
    - role: kube_init
      vars:
        become: false
      