---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/all.yml
  tasks:
    - name: Validate if required variables are present in environment
      fail:
        msg: AWS_ACCESS_KEY or AWS_SECRET_KEY not defined
      when: "'AWS_ACCESS_KEY' not in ansible_env or 'AWS_SECRET_KEY' not in ansible_env"
      no_log: true

    - name: Set variables
      set_fact:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
      no_log: true

    - name: read deploy yaml
      include_vars:
        name: deploy_host_names
        dir: ../deploy_config.yaml

    - include_role: 
        name: ec2_setup
      loop: "{{deploy_host_names}}"
      loop_control:
        loop_var: 

- hosts: elkhosts
  gather_facts: false
  # become: true
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: /opt/secrets/jenkinskeypair.pem
  roles:
    - ec2_provision
    - kube_init
      