---
- name: check if kubectl exists
  command: which kubectl
  register: kubestat
  ignore_errors: yes

- name: install kubectl if does not exist and make it executable
  block:
    - name: update cache
      apt:
        update_cache: yes

    - name: install apt-transport-https and gnupg2
      apt:
        name:
          - apt-transport-https 
          - gnupg2

    - name: Add kube official GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: update cache
      apt:
        update_cache: yes

    - name: install kubectl
      apt:
        name: kubectl
  when: kubestat.stdout == ""
    